#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding set to 0px
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 0

# -- mouse settings --
# center mouse on window with focus
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier ctrl
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize
# when you drop a window on another window, stack the two. (Default: swap)
yabai -m config mouse_drop_action stack

# global settings
yabai -m config \
	window_origin_display default \
	auto_balance off \
	split_ratio 0.50 \
	window_shadow on \
	window_opacity off \
	active_window_opacity 1.0 \
	normal_window_opacity 0.90 \
	external_bar off:40:0 \
	menubar_opacity 1.0 \
	display_arrangement_order default \
	window_zoom_persist on \
	window_animation_duration 0.0 \
	window_animation_easing ease_out_circ \
	window_opacity_duration 0.0 \
	insert_feedback_color 0xffd75f5f \
	split_type auto

# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^System Information$" manage=off sticky=on
yabai -m rule --add app="^Activity Monitor$" manage=off sticky=on
yabai -m rule --add app="^OrbStack$" manage=off sticky=on
yabai -m rule --add app="^Finder$" manage=off sticky=on
yabai -m rule --add app="^OpenCat$" manage=off sticky=on

echo "yabai configuration loaded.."
